import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { NavLinks } from "@/app/components/nav-links";
import "./globals.css";
import AnimationProvider from "./provider/AnimationProvider";
import { RouterWrapperProvider } from "./provider/RouterWrapperProvider";

const inter = Inter({ subsets: ["latin"] });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RouterWrapperProvider>
          <AnimationProvider>
            <NavLinks />
            <main>{children}</main>
          </AnimationProvider>
        </RouterWrapperProvider>
      </body>
    </html>
  );
}
